FROM node:16

WORKDIR /app

# Copy only the package.json file and install dependencies
COPY frontend/package.json /app/
COPY frontend/package-lock.json /app/
RUN npm install

# Copy the entire frontend project
COPY frontend /app/

CMD ["npm", "run", "start"]
